import java.util.ArrayList;

public class GameOverPanel extends SistakaPanel {
    // get list of users from homegui.java
    ArrayList<User> users = HomeGUI.getUsers();
    public GameOverPanel(HomeGUI main){
        super(main);
        initComponents(); // init panel
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        skorAndaLabel = new javax.swing.JLabel();
        gameOverLabel = new javax.swing.JLabel();
        welcomePanel = new javax.swing.JPanel();
        kembaliButton = new javax.swing.JButton();
        buttonPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(102, 102, 255));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setLayout(null);

        skorAndaLabel.setFont(new java.awt.Font("Super Legend Boy", 1, 18)); // NOI18N
        skorAndaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        skorAndaLabel.setText("SKOR ANDA: ");
        add(skorAndaLabel);
        skorAndaLabel.setBounds(40, 230, 430, 50);

        gameOverLabel.setFont(new java.awt.Font("Super Legend Boy", 1, 18)); // NOI18N
        gameOverLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameOverLabel.setText("GAME OVER ! !");
        add(gameOverLabel);
        gameOverLabel.setBounds(40, 200, 430, 30);

        welcomePanel.setBackground(new java.awt.Color(255, 102, 255));
        welcomePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        add(welcomePanel);
        welcomePanel.setBounds(100, 190, 310, 90);

        kembaliButton.setBackground(new java.awt.Color(102, 255, 102));
        kembaliButton.setFont(new java.awt.Font("Super Legend Boy", 0, 12)); // NOI18N
        kembaliButton.setText("KEMBALI");
        kembaliButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });
        add(kembaliButton);
        kembaliButton.setBounds(180, 400, 160, 40);

        buttonPanel.setBackground(new java.awt.Color(51, 51, 51));
        buttonPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        add(buttonPanel);
        buttonPanel.setBounds(170, 390, 180, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
        main.setPanel("mainMenu");
    }//GEN-LAST:event_kembaliButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel gameOverLabel;
    private javax.swing.JButton kembaliButton;
    private javax.swing.JLabel skorAndaLabel;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refresh() {
        User user = main.getUser();
        skorAndaLabel.setText("SKOR ANDA: " + user.getSkor());
        
    }

}

