import javax.swing.*;
import java.awt.*;
import java.util.concurrent.ThreadLocalRandom;

public class QuestionPanel extends SistakaPanel {
    public QuestionPanel(HomeGUI main){
        super(main);
        initComponents(); // init panel
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pertanyaanKeLabel = new javax.swing.JLabel();
        questionTextArea = new javax.swing.JTextArea();
        answerTextField = new javax.swing.JTextField();
        welcomePanel = new javax.swing.JPanel();
        answerButton = new javax.swing.JButton();
        buttonPanel = new javax.swing.JPanel();
        heart3 = new javax.swing.JLabel();
        heart1 = new javax.swing.JLabel();
        heart2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 255));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(null);

        pertanyaanKeLabel.setFont(new java.awt.Font("Super Legend Boy", 1, 14)); // NOI18N
        pertanyaanKeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pertanyaanKeLabel.setText("PERTANYAAN KE - ");
        add(pertanyaanKeLabel);
        pertanyaanKeLabel.setBounds(30, 10, 450, 120);

        questionTextArea.setBackground(new java.awt.Color(255, 102, 255));
        questionTextArea.setColumns(20);
        questionTextArea.setFont(new java.awt.Font("Super Legend Boy", 0, 12)); // NOI18N
        questionTextArea.setLineWrap(true);
        questionTextArea.setRows(5);
        questionTextArea.setText("QQQ");
        questionTextArea.setBorder(null);
        add(questionTextArea);
        questionTextArea.setBounds(40, 90, 430, 150);

        answerTextField.setFont(new java.awt.Font("Super Legend Boy", 0, 12)); // NOI18N
        answerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerTextFieldActionPerformed(evt);
            }
        });
        add(answerTextField);
        answerTextField.setBounds(100, 320, 310, 40);

        welcomePanel.setBackground(new java.awt.Color(255, 102, 255));
        welcomePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        welcomePanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );

        add(welcomePanel);
        welcomePanel.setBounds(30, 40, 450, 210);

        answerButton.setBackground(new java.awt.Color(102, 255, 102));
        answerButton.setFont(new java.awt.Font("Super Legend Boy", 0, 12)); // NOI18N
        answerButton.setText("ANSWER");
        answerButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        answerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerButtonActionPerformed(evt);
            }
        });
        add(answerButton);
        answerButton.setBounds(180, 400, 160, 40);

        buttonPanel.setBackground(new java.awt.Color(51, 51, 51));
        buttonPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        add(buttonPanel);
        buttonPanel.setBounds(170, 390, 180, 60);

        heart3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smol.png"))); // NOI18N
        add(heart3);
        heart3.setBounds(290, 260, 40, 40);

        heart1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smol.png"))); // NOI18N
        add(heart1);
        heart1.setBounds(190, 260, 40, 40);

        heart2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/smol.png"))); // NOI18N
        add(heart2);
        heart2.setBounds(240, 260, 40, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void answerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerTextFieldActionPerformed

    private void answerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerButtonActionPerformed
        // TODO add your handling code here:
        User user = main.getUser();
        String answer = Questions.getAnswerFromQuestion(questionTextArea.getText());
        
        if (answerTextField.getText().equalsIgnoreCase(answer)) { // case insensitive
            user.correct();
        } else {
            user.wrong();
        }

        refresh();
        
    }//GEN-LAST:event_answerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerButton;
    private javax.swing.JTextField answerTextField;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel heart1;
    private javax.swing.JLabel heart2;
    private javax.swing.JLabel heart3;
    private javax.swing.JLabel pertanyaanKeLabel;
    private javax.swing.JTextArea questionTextArea;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refresh() {
        User user = main.getUser();

        if (user.getHealth() < 1) { // kalo heart udah habis balik ke main menu
            main.setPanel("gameOver");
        }

        int randomNum = ThreadLocalRandom.current().nextInt(1, Questions.getQuestionAnswerCount() + 1);
        String question = Questions.getQuestion(randomNum);

        pertanyaanKeLabel.setText("Pertanyaan ke-" + user.getQuestionCounter());
        questionTextArea.setText(question);

        // nampilin jumlah heart sesuai dengan health
        switch (user.getHealth()) {
            case 3:
                heart1.setVisible(true);
                heart2.setVisible(true);
                heart3.setVisible(true);
                break;
            case 2:
                heart1.setVisible(true);
                heart2.setVisible(true);
                heart3.setVisible(false);
                break;
            case 1:
                heart1.setVisible(false);
                heart2.setVisible(true);
                heart3.setVisible(false);
                break;
        }
        
        user.incQuestionCounter(); // increment question counter
        
    }

}

