import javax.swing.*;
import java.util.ArrayList;

public class RegisterPanel extends SistakaPanel {
    // get list of users from homegui.java
    ArrayList<User> users = HomeGUI.getUsers();
    public RegisterPanel(HomeGUI main){
        super(main);
        initComponents(); // init panel
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        triviaArkan = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        welcomePanel = new javax.swing.JPanel();
        nameTextField = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();
        buttonPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(102, 102, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(null);

        triviaArkan.setFont(new java.awt.Font("Super Legend Boy", 1, 18)); // NOI18N
        triviaArkan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        triviaArkan.setText("NAMA ANDA");
        add(triviaArkan);
        triviaArkan.setBounds(40, 110, 430, 50);

        welcome.setFont(new java.awt.Font("Super Legend Boy", 1, 18)); // NOI18N
        welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome.setText("SILAHKAN MASUKKAN");
        add(welcome);
        welcome.setBounds(40, 80, 430, 30);

        welcomePanel.setBackground(new java.awt.Color(255, 102, 255));
        welcomePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        add(welcomePanel);
        welcomePanel.setBounds(100, 70, 310, 90);

        nameTextField.setFont(new java.awt.Font("Super Legend Boy", 0, 12)); // NOI18N
        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        add(nameTextField);
        nameTextField.setBounds(100, 250, 310, 40);

        startButton.setBackground(new java.awt.Color(102, 255, 102));
        startButton.setFont(new java.awt.Font("Super Legend Boy", 0, 12)); // NOI18N
        startButton.setText("START");
        startButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        add(startButton);
        startButton.setBounds(180, 310, 160, 40);

        buttonPanel.setBackground(new java.awt.Color(51, 51, 51));
        buttonPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        add(buttonPanel);
        buttonPanel.setBounds(170, 300, 180, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        String name = nameTextField.getText();    
        boolean isAvailable = HomeGUI.userAvailable(name);

        if (!name.isEmpty()) {
            if (isAvailable) {// name available
                User user = new User(name);
                users.add(user);
                main.setUser(user);
                main.setPanel("question");

            } else {
                JOptionPane.showMessageDialog(this, "Nama sudah ada di database!", "Warning", JOptionPane.WARNING_MESSAGE);
                refresh();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nama tidak boleh kosong!", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_startButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel triviaArkan;
    private javax.swing.JLabel welcome;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void refresh() {
        nameTextField.setText("");
    }

}

